# Utilise une image officielle PHP avec Apache
FROM php:8.2-apache

# Active le module Apache rewrite (utile pour .htaccess)
RUN a2enmod rewrite

# Copie tout le projet dans le conteneur
COPY . /var/www/html/

# Définit le dossier public comme racine du serveur web
WORKDIR /var/www/html/public

# Autorise l'utilisation des fichiers .htaccess
RUN sed -i 's/AllowOverride None/AllowOverride All/g' /etc/apache2/apache2.conf

# Ouvre le port 80
EXPOSE 80